# Generated by Django 2.2.5 on 2019-09-24 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0002_auto_20190924_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamfile',
            old_name='name',
            new_name='title',
        ),
    ]
